version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
        NEXT_PUBLIC_DO_ACCESS_KEY: ${NEXT_PUBLIC_DO_ACCESS_KEY}
        NEXT_PUBLIC_DO_SECRET_KEY: ${NEXT_PUBLIC_DO_SECRET_KEY}
        NEXT_PUBLIC_DO_REGION: ${NEXT_PUBLIC_DO_REGION}
        NEXT_PUBLIC_DO_ORIGIN_ENDPOINT: ${NEXT_PUBLIC_DO_ORIGIN_ENDPOINT}
        NEXT_PUBLIC_DO_BUCKET_NAME: ${NEXT_PUBLIC_DO_BUCKET_NAME}
    working_dir: /app
    ports:
      - "3000:3000"
    image: registrasi-itbx
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
